Repository CliMA/Thermodynamics.jl, pull requests merged in 2021-09, with the labels that each got.

#43 Fix broken link
  docs/src/Formulation.md
Labels: documentation, bugfix :bug:

#47 Rename PhaseEquil outer constructor to PhaseEquil_ρeq, change arg order
  docs/ThreeDimensionalInput.jl
  docs/src/API.md
  docs/src/index.md
  src/relations.jl
  src/states.jl
  test/data_tests.jl
  test/relations.jl
  test/runtests_gpu.jl
  test/update_constructor_data.jl
Labels: breaking changes :boom:

#53 Write saturation adjustment methods more compactly
  src/relations.jl
Labels: Refactor :gear:

#52 Add pressure to ts and make PhaseEquil_pθq more consistent
  Project.toml
  docs/src/API.md
  src/relations.jl
  src/states.jl
  test/relations.jl
Labels: bugfix :bug:

#55 Use @print for gpu in sat adjust pθq, bump version
  Project.toml
  src/relations.jl
Labels: bugfix :bug:

#56 Qualify methods / types in src/
  src/TemperatureProfiles.jl
  src/TestedProfiles.jl
  src/Thermodynamics.jl
  src/config_numerical_method.jl
  src/isentropic.jl
  src/relations.jl
  src/states.jl
Labels: Refactor :gear:
