Repository CliMA/Thermodynamics.jl, pull requests merged in 2023-09, with the labels that each got.

#152 expand micro benchmark
  perf/flops.jl
Labels: Performance monitoring :mag::rocket:, Launch Buildkite

#153 Manually perform common subexpression elimination
  src/relations.jl
Labels: Performance :rocket:, Launch Buildkite

#155 Update RootSolvers, avoid recomputation
  Project.toml
  gpuenv/Project.toml
  src/config_numerical_method.jl
  src/relations.jl
  test/Project.toml
Labels: Performance :rocket:, Launch Buildkite

#163 Add and fix aqua tests
  test/Project.toml
  test/aqua.jl
  test/runtests.jl
Labels: Launch Buildkite

#164 Upgrade to Julia 1.9
  .buildkite/pipeline.yml
  .github/workflows/CodeCov.yml
  .github/workflows/JuliaFormatter.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: Launch Buildkite

#165 Change supersaturation definition
  src/relations.jl
  test/relations.jl
Labels: Launch Buildkite
