Repository CliMA/Thermodynamics.jl, pull requests merged in 2024-02, with the labels that each got.

#191 Remove unused argument in virtual_temperature
  src/relations.jl
  test/relations.jl
Labels: Launch Buildkite

#192 Fix zero `q_tot` edge case
  Project.toml
  src/relations.jl
Labels: bugfix :bug:, Launch Buildkite

#194 Replace AbstractFloat with Real
  ext/CreateParametersExt.jl
  src/TemperatureProfiles.jl
  src/isentropic.jl
  src/relations.jl
Labels: Launch Buildkite

#195 Remove type casting of parameters
  src/TemperatureProfiles.jl
  src/TestedProfiles.jl
  src/config_numerical_method.jl
  src/isentropic.jl
  src/relations.jl
Labels: Launch Buildkite

#193 Use ClimaParameters T_init_min, with new T_min value
  Project.toml
  ext/CreateParametersExt.jl
  gpuenv/Project.toml
  perf/Project.toml
  src/Parameters.jl
  src/config_numerical_method.jl
  src/relations.jl
  test/Project.toml
Labels: Launch Buildkite

#199 Add promoting constructors for Dual number support
  src/relations.jl
  src/states.jl
Labels: Launch Buildkite

#201 Add more promotion and remove restriction on SA tolerance
  Project.toml
  src/relations.jl
Labels: Launch Buildkite

#203 Remove type restriction on e_pot
  Project.toml
  src/relations.jl
Labels: Launch Buildkite

#205 Add flop count perf job back in
  .buildkite/pipeline.yml
  perf/Project.toml
  perf/flops.jl
Labels: Performance monitoring :mag::rocket:, Launch Buildkite

#206 Switch CI to new partition
  .buildkite/JuliaProject.toml
  .buildkite/pipeline.yml
Labels: Launch Buildkite

#202 Update to ClimaParams v0.10
  Project.toml
  docs/Project.toml
  docs/src/Clausius_Clapeyron.jl
  docs/src/TemperatureProfiles.md
  docs/src/TestedProfiles.md
  docs/src/saturation_adjustment.jl
  ext/CreateParametersExt.jl
  gpuenv/Project.toml
  perf/Project.toml
  perf/allocs.jl
  perf/common.jl
  perf/common_micro_bm.jl
  perf/kernel_bm.jl
  src/Parameters.jl
  src/Thermodynamics.jl
  test/Project.toml
  test/TemperatureProfiles.jl
  test/relations.jl
  test/runtests_gpu.jl
Labels: Launch Buildkite
