Repository CliMA/Thermodynamics.jl, pull requests merged in 2024-01, with the labels that each got.

#175 Fix aqua tests
  Project.toml
  perf/alloc_per_constructor.jl
  perf/allocs.jl
  test/aqua.jl
  test/runtests.jl
  test/runtests_gpu.jl
Labels: Launch Buildkite

#174 (Try 2) Improve the explanation surrounding "virtual temperature" and a hypothetical "density temperature"
  docs/src/Formulation.md
Labels: Launch Buildkite

#176 Move parameter constructor to a package extension, use name maps
  Project.toml
  docs/src/Clausius_Clapeyron.jl
  docs/src/TemperatureProfiles.md
  docs/src/TestedProfiles.md
  docs/src/saturation_adjustment.jl
  ext/CreateParametersExt.jl
  gpuenv/Project.toml
  perf/common.jl
  perf/common_micro_bm.jl
  perf/jet.jl
  perf/microbenchmarks.jl
  src/Parameters.jl
  src/Thermodynamics.jl
  test/Project.toml
  test/TemperatureProfiles.jl
  test/data_tests.jl
  test/relations.jl
  test/runtests_gpu.jl
Labels: Launch Buildkite

#179 Bump patch version
  Project.toml
Labels: Launch Buildkite

#181 Convert data-based test to sampling-based test
  test/Project.toml
  test/data_tests.jl
  test/relations.jl
  test/update_constructor_data.jl
Labels: tests, Launch Buildkite

#180 Update deps and julia version
  .buildkite/pipeline.yml
  .github/workflows/CodeCov.yml
  .github/workflows/DocCleanUp.yml
  .github/workflows/JuliaFormatter.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/invalidations.yml
  Project.toml
  docs/Project.toml
  gpuenv/Project.toml
  perf/Project.toml
  perf/common.jl
  perf/common_micro_bm.jl
  test/Project.toml
  test/relations.jl
  test/runtests_gpu.jl
Labels: Dependencies :spider_web:, Launch Buildkite

#182 Add kernel benchmarks
  .buildkite/pipeline.yml
  gpuenv/Project.toml
  perf/Project.toml
  perf/kernel_bm.jl
  src/relations.jl
  test/runtests_gpu.jl
Labels: Performance monitoring :mag::rocket:, Launch Buildkite

#184 Update kernel benchmark
  perf/kernel_bm.jl
Labels: Performance monitoring :mag::rocket:, Launch Buildkite

#185 Update virtual_dry_static_energy
  src/relations.jl
  test/relations.jl
Labels: Launch Buildkite

#183 Inlining everything
  src/Parameters.jl
  src/Thermodynamics.jl
  src/config_numerical_method.jl
  src/isentropic.jl
  src/relations.jl
  src/states.jl
Labels: Launch Buildkite

#186 Bump patch for new release
  Project.toml
Labels: Release

#187 remove reference temperature in virtual DSE
  Project.toml
  src/relations.jl
  test/relations.jl
Labels: Launch Buildkite

#188 Skip inlining PhaseEquil for equilibrium phases
  Project.toml
  src/relations.jl
Labels: Performance :rocket:, Launch Buildkite
